name: Build Tests, Lints Oh My!

on:
  pull_request:
    branches:
      - '**'

env:
  NODE_VERSION: '21'
  NEXT_PUBLIC_URL: 'http://localhost:3000'
  NEXT_PUBLIC_LOCALE: 'en-gb'
  MEMBERS_URL: "http://localhost:3001"
  COGNITO_APP_CLIENT_ID: "fake"
  COGNITO_USER_POOL_ID: "eu-west-1_8IEnjoy"
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: main/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('main/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          cd main
          yarn install

      - name: Run Lint
        run: |
          cd main
          yarn lint

      - name: Build Project
        env:
          NEXT_PUBLIC_URL: ${{ env.MEMBERS_URL }}
          COGNITO_APP_CLIENT_ID: ${{ env.COGNITO_APP_CLIENT_ID }}
          COGNITO_USER_POOL_ID: ${{ env.COGNITO_USER_POOL_ID }}
        run: |
          cd main
          yarn build 

      - name: Run Tests
        env:
          NEXT_PUBLIC_URL: ${{ env.NEXT_PUBLIC_URL }}
          NEXT_PUBLIC_LOCALE: ${{ env.NEXT_PUBLIC_LOCALE }}
        run: |
          cd main
          yarn test:jest

      - name: Jest Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          path: main/coverage/coverage-summary.json
