name: Run Jest Tests for me

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Install Dependencies
      run: |
        cd main
        yarn install

    - name: Run Lint
      run: |
        cd main
        npm run lint

    - name: Run Jest
      env:
        NEXT_PUBLIC_URL: 'http://localhost:3000'
        NEXT_PUBLIC_LOCALE: 'en-gb'
      run: |
        cd main
        npm run test:jest
