name: Build Tests, Lints Oh My!

on:
  pull_request:
    branches:
      - '**'

env:
  NODE_VERSION: '21'
  BUILD_TIMEOUT: 2
  TEST_TIMEOUT: 2
  LINT_TIMEOUT: 2

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ env.LINT_TIMEOUT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: main/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('main/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        run: |
          cd main
          yarn install

      - name: Run Lint
        run: |
          cd main
          npm run lint  # Assuming you have a lint script defined in your package.json

  build:
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: ${{ env.BUILD_TIMEOUT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: main/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('main/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        run: |
          cd main
          yarn install

      - name: Build Project
        run: |
          cd main
          npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: ${{ env.TEST_TIMEOUT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: main/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('main/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        run: |
          cd main
          yarn install

      - name: Run Tests
        env:
          NEXT_PUBLIC_URL: 'http://localhost:3000'
          NEXT_PUBLIC_LOCALE: 'en-gb'
        run: |
          cd main
          npm test
